### ISSUE TITLE
short description 

### ISSUE THREAD

**Issue by cherepanovic** [HotaekHan/classification_uncertainty#1]
could you describe in abstract your experiments

thanks

**Comment by HotaekHan** [comment]
hi, updated the readme. check out please :)

**Comment by cherepanovic** [comment]
I meant an abstract of your doing... what is the purpose and you exactly did or is there any papers already published?

**Comment by HotaekHan** [comment]
@cherepanovic ok, this experiment compares how well measure the uncertainty. the uncertainty is an important thing for a robust classifier. 
Google has published a paper related to this topic.
https://arxiv.org/abs/1906.02530
